<?php
$targets = [
  'app/Views/pages/detail.php',
  'app/Views/pages/series.php',
  'app/Views/pages/peliculas.php',
  'app/Views/pages/gesCom.php',
  'app/Views/pages/gesUs.php',
  'public/assets/js/detail-data.js',
  'public/assets/js/layout.js',
  'public/assets/js/filters.js',
  'public/assets/js/load-more.js',
  'public/assets/js/search.js',
];
$replacements = [
  "PuntuaciÃƒÂ³n" => "Puntuación",
  "Puntuación" => "Puntuación",
  "En emisiÃƒÂ³n" => "En emisión",
  "En emisiÃ³n" => "En emisión",
  "DuraciÃƒÂ³n" => "Duración",
  "Duración" => "Duración",
  "AcciÃƒÂ³n" => "Acción",
  "Acción" => "Acción",
  "FantasÃƒÂ­a" => "Fantasía",
  "Fantasía" => "Fantasía",
  "AÃƒÂ±adir a Mi Lista" => "Añadir a Mi Lista",
  "GalerÃƒÂ­a" => "Galería",
  "InformaciÃƒÂ³n" => "Información",
  "Información" => "Información",
  "tÃƒÂ­tulos" => "títulos",
  "títulos" => "títulos",
  "opiniÃƒÂ³n" => "opinión",
  "opinión" => "opinión",
  "tÃƒÂ­tulo" => "título",
  "título" => "título",
  "SESIÃƒâ€œN" => "SESIÓN",
  "SÃƒÂ© breve, claro y respetuoso." => "Sé breve, claro y respetuoso.",
  "calificaciÃƒÂ³n" => "calificación",
  "calificación" => "calificación",
  "puntuaciÃƒÆ’Ã‚Â³n" => "puntuación",
  "Tu opiniÃƒÂ³n ayuda a la comunidad." => "Tu opinión ayuda a la comunidad.",
  "Ver mÃƒÂ¡s comentarios" => "Ver más comentarios",
  "Ver mÃ¡s comentarios" => "Ver más comentarios",
  "Ã‚Â¿EstÃƒÂ¡s seguro de que deseas borrar este comentario? Esta acciÃƒÂ³n no se puede deshacer." => "¿Estás seguro de que deseas borrar este comentario? Esta acción no se puede deshacer.",
  "CuÃƒÂ©ntanos por quÃƒÂ© quieres reportar este comentario..." => "Cuéntanos por qué quieres reportar este comentario...",
  "espaÃƒÂ±ol" => "español",
  "español" => "español",
  "TodavÃƒÂ­a no hay comentarios para este filtro." => "Todavía no hay comentarios para este filtro.",
  "Todavía" => "Todavía",
  "Debes iniciar sesiÃƒÂ³n para comentar." => "Debes iniciar sesión para comentar.",
  "Debes iniciar sesión para comentar." => "Debes iniciar sesión para comentar.",
  "inicializaciÃƒÂ³n" => "inicialización",
  "inicializaciÃ³n" => "inicialización",
  "Â¿Deseas marcar este comentario como revisado? Luego de hacerlo no se podrá cambiar." => "¿Deseas marcar este comentario como revisado? Luego de hacerlo no se podrá cambiar.",
  "Â¿Deseas quitar el bloqueo de " => "¿Deseas quitar el bloqueo de ",
  "Â¿Deseas eliminar para siempre a " => "¿Deseas eliminar para siempre a ",
  "borrará toda su información" => "borrará toda su información",
  "año" => "año",
  "Película" => "Película",
  "Películas" => "Películas",
  "mÃƒÂ¡s" => "más",
  "mÃ¡s" => "más",
  "catÃƒÂ¡logo" => "catálogo",
  "catálogo" => "catálogo",
  "IntÃƒÂ©ntalo" => "Inténtalo",
  "IntÃ©ntalo" => "Inténtalo",
  "PelÃ­Â­culas" => "Películas",
  "FantasÃ­Â­a" => "Fantasía",
  "Anime y PelÃ­Â­culas" => "Anime y Películas",
  "En pagina de peliculas: mostrar el año de publicaciÃ³n y abajo a la izquierda." => "En página de películas: mostrar el año de publicación abajo a la izquierda.",
  "sesión" => "sesión",
  "contraseña" => "contraseña",
  "Título" => "Título",
  "ClasificaciÃ³n" => "Clasificación",
  "EmisiÃ³n" => "Emisión",
  "PrÃ³ximamente" => "Próximamente",
  "PÃºblico" => "Público",
];
foreach ($targets as $path) {
  $full = __DIR__ . '/' . str_replace('/', DIRECTORY_SEPARATOR, $path);
  $content = file_get_contents($full);
  $updated = strtr($content, $replacements);
  if ($updated !== $content) {
    file_put_contents($full, $updated);
    echo $path, PHP_EOL;
  }
}
?>
